### ISSUE TITLE
doesn't work.. I type in "an {task name}" and then nothing happens

### ISSUE THREAD

**Issue by zendude213** [hkob/notion-tools-alfred-workflow#1]
Hello there:

- I duplicated your Notion project template and configured the variables
- I created Notion API token
- I shared Project DB and Task DB with Notion Integration associated with my Notion API token
- I configured the workflow variables as follows
>> ![nt variables png](https://user-images.githubusercontent.com/59263556/147631146-ddb54429-6b6b-4732-b5bd-b92b376b8d7f.png)
- I got the PROJECT_NAME "projects" from..
>> ![ntprj png](https://user-images.githubusercontent.com/59263556/147631371-3bde3032-c4cb-4483-b03e-f728f261656d.png)
- I got the PROJECT_LINK "projects" from..
>> ![nt-link png](https://user-images.githubusercontent.com/59263556/147631490-39e01fa0-cfd0-4b51-800b-4fbdb9b7ec4f.png)

Nothing worked... every time I type in "an {task name}" it prompts for the name of project I want to link it to but there is no dropdown and typing a project name in has no effect

Can you help?

Thanks!

**Comment by zendude213** [comment]
nevermind.. I figured it out... had to remove "?v" from DB ID and change PROJECT_NAME value from "Projects" to "name" -- boy was that confusing :-)

**Comment by hkob** [comment]
DATABASE_ID and TASK_ID are only `32-character hexadecimal number`.
I'm sorry that you have already solved it.
I added the explanation to the README.
Thank you for your comment.
